# fly.io 배포 설정 파일

app = "notion-to-blog"  # 실제 앱 이름으로 변경 필요
primary_region = "nrt"  # 도쿄 리전 (한국과 가까움)

[build]
  builder = "paketobuildpacks/builder-jammy-base"

[env]
  PORT = "8501"
  STREAMLIT_SERVER_PORT = "8501"
  STREAMLIT_SERVER_ADDRESS = "0.0.0.0"

[http_service]
  internal_port = 8501
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0

[[http_service.checks]]
  grace_period = "30s"
  interval = "15s"
  method = "GET"
  timeout = "5s"
  path = "/healthz"

[vm]
  size = "shared-cpu-1x"
  memory = "512mb"

# 환경 변수는 fly secrets 명령어로 설정
# fly secrets set NOTION_TOKEN=your_token
# fly secrets set NOTION_DATABASE_ID=your_database_id